version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - djd-starter-kit-s3-deployment # context is named the same in both orgs
parameters:
  PREVIEW:
    type: boolean
    default: FALSE
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    working_directory: ~/project
    executor:
      name: node/default
      tag: '20.11-browsers'
    steps:
      - checkout
      - run:
          name: Install Doppler CLI
          command: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh -s -- --no-install --no-package-manager
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: ./doppler run --command "npm run build"
      - store_artifacts:
          name: Store artifacts (dist)
          path: dist/
      - deploy:
          name: Deploy
          command: |
            if [ "<< pipeline.parameters.PREVIEW >>" == "true" ]
            then
              ./doppler run --command "npm run deploy -- --confirm --preview"
            else
              ./doppler run --command "npm run deploy -- --confirm"
            fi
      - run:
          name: Check accessibility of deployed site
          command: |
            if [ "<< pipeline.parameters.PREVIEW >>" == "true" ]
            then
              npm run a11y:preview
            else
              npm run a11y
            fi
      # - run:
      #     name: General QA tests
      #     command: |
      #       if [ $CIRCLE_BRANCH = "main" ]
      #       then
      #         npm run test
      #       else
      #         npm run test || echo "General QA tests failed. Continuing anyway"
      #       fi
