version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.10.2-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          # NB. this also does bower install as postinstall step
          command: npm install
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          name: Store artifacts (dist)
          path: dist/
      - store_artifacts:
          name: Store artifact (package-lock.json)
          path: package-lock.json
      - run:
          name: General QA checks
          command: npm run qa
      - deploy:
          name: Deploy
          command: |
            if [ "$PREVIEW" == "true" ]
            then
              npm run deploy -- --confirm --preview
            else
              npm run deploy -- --confirm
            fi
      - run:
          name: Check accessibility of deployed site
          command: |
            if [ "$PREVIEW" == "true" ]
            then
              npm run check-accessibility:preview
            else
              npm run check-accessibility
            fi
